# Generated by Django 4.1.5 on 2026-10-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menuitem_delete_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='reservation_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_slot',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('reservation_date', 'reservation_slot')},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='no_of_guests',
        ),
    ]
